### ISSUE TITLE
Plugin documentation of the jQA Spring Plugin wrongly rendered

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-manual#6]
Out user @hwellmann reported that since version 1.5.0 the documentation of the jQA Spring Plugin is not properly included and rendered in the jQA manual.

I can confirm this also for the current development version. I suppose this is a subtle bug in the XSLT scripts we use.

**Comment by DirkMahler** [comment]
That's caused by some namespace fun while performing the XSL transformation from plugin descriptors (`jqassistant-plugin.xml`) to Asciidoc. Fix will be provided that is namespace agnostic.
